version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root
